In [ ]:
import joblib
import pandas as pd

def summarize_scaler(scaler):
    """
    Returns a DataFrame with information about a fitted MinMaxScaler.
    
    Parameters
    ----------
    scaler : sklearn.preprocessing.MinMaxScaler
        The already fitted scaler.
    
    Returns
    -------
    pd.DataFrame
        Columns: feature, data_min, data_max, feature_range_min,
                 feature_range_max, scale, min.
    """
    # variable names
    features = scaler.feature_names_in_
    
    # decompose feature_range into min and max
    fr_min, fr_max = scaler.feature_range
    
    # build DataFrame
    df = pd.DataFrame({
        'feature':          features,
        'data_min':         scaler.data_min_,
        'data_max':         scaler.data_max_,
        'feature_range_min': fr_min,
        'feature_range_max': fr_max,
        'scale':            scaler.scale_,
        'min':              scaler.min_,
    })
    return df

In [ ]:
import joblib
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

def summarize_scaler(fitxer: str) -> pd.DataFrame:
    """
    Loads a MinMaxScaler from a file (can be .lib, .joblib, .pkl, etc.)
    and returns a DataFrame with its information.
    
    Parameters
    ----------
    fitxer : str
        Path to the file where the scaler is saved.
    
    Returns
    -------
    pd.DataFrame
        Columns: feature, data_min, data_max, feature_range_min,
                 feature_range_max, scale, min.
    """
    # load the scaler (the extension doesn't matter as long as it's a joblib dump)
    scaler = joblib.load(fitxer)
    
    if not isinstance(scaler, MinMaxScaler):
        raise TypeError(f"The loaded object is not a MinMaxScaler (it is {type(scaler)}).")
    

    # decompose feature_range into min and max
    fr_min, fr_max = scaler.feature_range
    
    # build DataFrame
    df = pd.DataFrame({
        'data_min':          scaler.data_min_,
        'data_max':          scaler.data_max_,
        'feature_range_min': fr_min,
        'feature_range_max': fr_max,
        'scale':             scaler.scale_,
        'min':               scaler.min_,
    })
    return df

In [3]:
summarize_scaler("gbm_v1.lib")

,data_min,data_max,feature_range_min,feature_range_max,scale,min
0,-132.065930,167.357880,-1.0,1.0,0.006679,-0.117866
1,-132.065930,167.357880,-1.0,1.0,0.006679,-0.117866
2,-0.027172,171.700371,-1.0,1.0,0.011646,-0.999684
3,-49.811550,99.998580,-1.0,1.0,0.013350,-0.335004
4,800.000000,4000.000000,-1.0,1.0,0.000625,-1.500000

In [4]:
summarize_scaler("gbm_v2.lib")

,data_min,data_max,feature_range_min,feature_range_max,scale,min
0,-5.0,200.0,-1,1,0.009756,-0.951220
1,-5.0,200.0,-1,1,0.009756,-0.951220
2,3.0,70.0,-1,1,0.029851,-1.089552
3,0.0,100.0,-1,1,0.020000,-1.000000
4,0.0,4000.0,-1,1,0.000500,-1.000000

In [5]:
summarize_scaler("rl.lib")

,data_min,data_max,feature_range_min,feature_range_max,scale,min
0,-5.0,200.0,-1,1,0.009756,-0.951220
1,-5.0,200.0,-1,1,0.009756,-0.951220
2,3.0,70.0,-1,1,0.029851,-1.089552
3,0.0,100.0,-1,1,0.020000,-1.000000
4,0.0,4500.0,-1,1,0.000444,-1.000000